### ISSUE TITLE
Website feedback collection for V2

### ISSUE THREAD

**Issue by DBecane** [beamer-bridge/www.beamerbridge.com#1]
## Description

This issue is meant to gather feedback collectively and prioritize the must-do's for the next iteration. Please leave your feedback as comments and @olympe-silve can then organize and prioritize topics.

**Comment by DinaBB** [comment]
@olympe-silve career link in the footer to be added to the website 2.0 💃🏻

https://web3.career/web3-companies/beamer-bridge

**Comment by istankovic** [comment]
Is this issue still relevant?

**Comment by DinaBB** [comment]
It is, and I am about to update it :p

**Comment by DinaBB** [comment]
@GabrielBuragev @manuelwedler 

As discussed in our meeting. Here are the additional small additional changes to be made: 

All of these changes will be reflected on Figma by @olympe-silve anyway. So this issue and the related #4 can serve as a checklist to make sure all the edits have been done. 

- Website: Medium Carousel - Showcasing the latest blogposts between 'How section' and 'Join the community'. (research to be done here - might be worth creating an issue? @GabrielBuragev / @manuelwedler )
- Website: Separate footer link in 2 sections (@olympe-silve knows and will reflect it on Figma)
- Website: Add 'Career' in the footer (also most likely reflected on Figma)
- Website: Link to the terms & conditions
- Mistake in copy: 
![image](https://user-images.githubusercontent.com/85872820/185112048-411806c5-9e1e-45b6-961f-cd96bda1fb9f.png)

**Comment by olympe-silve** [comment]
See #7 for a commentary on important links that should be made more visible / on header

**Comment by DBecane** [comment]
> #4

@GabrielBuragev @olympe-silve (FYI)

The last remaining change as per the comment above ^ is the implementation of the medium carousel. I have created this issue here #18 .

**Comment by DBecane** [comment]
> @GabrielBuragev @manuelwedler
> 
> As discussed in our meeting, here are the additional small additional changes to be made:
> 
> All of these changes will be reflected on Figma by @olympe-silve anyway. So this issue and the related #4 can serve as a checklist to make sure all the edits have been done.
> 
> * Website: Medium Carousel - Showcasing the latest blogposts between 'How section' and 'Join the community'. (research to be done here - might be worth creating an issue? @GabrielBuragev / @manuelwedler )
> * Website: Separate footer link in 2 sections (@olympe-silve knows and will reflect it on Figma)
> * Website: Add 'Career' in the footer (also most likely reflected on Figma)
> * Website: Link to the terms & conditions
> * Mistake in copy:
>   ![image](https://user-images.githubusercontent.com/85872820/185112048-411806c5-9e1e-45b6-961f-cd96bda1fb9f.png)

@GabrielBuragev @olympe-silve (FYI)

The last remaining change as per the comment above ^ is the implementation of the medium carousel. I have created this issue here #18 .

**Comment by andfletcher** [comment]
I am closing this issue since Dina pointed out that the last remaining todo is reflected in issue #18 . Please reopen if i am wrong.
