### ISSUE TITLE
Research possible medium carousel solutions

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/www.beamerbridge.com#15]
Follow up issue of #1 

We need to do a research on how to implement a Medium Carousel for showcasing the latest blogposts between 'How section' and 'Join the community'.

**Comment by GabrielBuragev** [comment]
Possible solution
---

Medium's RSS feed: 
https://help.medium.com/hc/en-us/articles/214874118-Using-RSS-feeds-of-profiles-publications-and-topics

**Comment by GabrielBuragev** [comment]
The Medium's RSS feed mentioned above will work however the implementation is not so straight forward as there is a need for proxying all requests to their RSS feed endpoints (read more [here](https://github.com/nasa8x/rss-to-json/issues/8#issuecomment-591420887)) due to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) issues.
That means we would need to spin up a proxy service (that just proxies the frontend request to Medium) on our own and host it on one of our servers or try to find another solution.

**Note:** Any other solution would mean that we host our own API endpoints somewhere for serving us this data.

@andfletcher @czepluch your thoughts?

**Comment by GabrielBuragev** [comment]
Proxy server implementation repo: https://github.com/Rob--W/cors-anywhere

A straightforward "git clone & dependency install" command is all it's needed to get this running.

**Comment by andfletcher** [comment]
Thank you @GabrielBuragev based on what you wrote and what i have read here:
https://www.pragm.co/post/should-you-use-a-carousel-on-your-website
https://medium.com/@Vincentxia77/design-mistake-you-are-still-using-website-carousel-deaf88a719a8
https://lsnrae.medium.com/if-you-must-use-a-carousel-make-it-accessible-977afd0173f4

I don't think it's worth it in general. I will align with Dina and Olympe a bit on it. 

@czepluch, what are your thoughts?

Also given the fact that the last medium article had sooooo low impressions we should probably just wait and see if medium is the right tool for beamer.

**Comment by czepluch** [comment]
I would agree with @andfletcher.

I think it's a good idea to have blogposts because it also gives us a way to track history in the project. But if we use Medium or Mirror or whatever doesn't matter to me.

**Comment by andfletcher** [comment]
I am closing this issue since research has been done. Next steps to be aligned and planned.
