### ISSUE TITLE
Edit Imprint Website + App

### ISSUE THREAD

**Issue by DBecane** [beamer-bridge/www.beamerbridge.com#23]
## Description

Jake has created new legal templates for imprint and privacy matters. See more [here](https://drive.google.com/drive/u/0/folders/17pkDimGVfiyrhyqLXN40JWbsRjBXkRSW). Therefore, we need to do the following: 

- [ ] @czepluch to prioritize this issue with @GabrielBuragev when suited 
- [x] ~~@olympe-silve + @GabrielBuragev to align on whether design input is needed~~
- [ ] Update the Imprint on both website + app. [Here is the copy](https://docs.google.com/document/d/1tRlYfd1MrokC1H6KcVWizgQOXHXZWxex8tW-J7X3dMs/edit)

**Comment by DBecane** [comment]
Let me know if there are any questions here and what the work and delivery date estimation looks like 🙏

**Comment by GabrielBuragev** [comment]
No design input is needed for this issue.
