### ISSUE TITLE
Add link to audit report

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/www.beamerbridge.com#30]
Since we will be posting the audit results we also want it to be easy accessible to our users on the website. This will lead to an easy access point for interested users.

The idea is that we will add a link in the footer of the main website that will link to a PDF that is stored within our Gdrive or GitHub (what ever is easier)

- [ ] Link to the audit report is added in the footer
- [ ] If people click on it it will open a new tab that will show the pdf

**Comment by DBecane** [comment]
I will be closing the design issue, let's continue here. 

recap from the design issue: 

Based on https://github.com/beamer-bridge/marketing/issues/128 we would like to add an 'Audit' mention in the footer. This will allow people to easily access the smart contract audit report if they want to. (PDF opening in a new tab)

See [connext as a reference.](https://www.connext.network/)

**Comment by andfletcher** [comment]
Just so you know, we will deploy a new version of our websites this week, including arbitrum support. 

!!!! NO ADDING OF THE AUDIT REPORT !!!!

We need to wait until all agents are offline before we add the audit report. So we will do a new deployment after the first one very shortly.

**Comment by DBecane** [comment]
This new website deployment will happen before us publicly announcing right?
Because I have an audit mention in the article

**Comment by DBecane** [comment]
@andfletcher here you go: https://drive.google.com/drive/folders/1BNPw5dUJA5eGtDCr80sxDcDNdkI5LAH3

**Comment by GabrielBuragev** [comment]
@DBecane File is not publicly accessible
