### ISSUE TITLE
Add Arbitrum logo

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/www.beamerbridge.com#31]
We need to add the Arbitrum logo in this section prior to the v1 mainnet launch:

![image](https://user-images.githubusercontent.com/18466333/212670816-36a6b05f-cbb1-490a-83f3-42f42d624569.png)

# Acceptance Criteria
- [x] Arbitrum logo is included in section

**Comment by DBecane** [comment]
- [ ] Add Arbitrum mention to the paragraph right above: 
- [ ]
