### ISSUE TITLE
Add "backed by" section to beamer website

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/www.beamerbridge.com#38]
## Description
We want to add a "backed by" section to beamer so that we can show who is part of the beamer ecosystem in regards to funding.

## Acceptance Criteria
- [ ] Add based on https://github.com/beamer-bridge/marketing/issues/198#issuecomment-1413319083

**Comment by DBecane** [comment]
As agreed with @olympe-silve - Let's not forget the very small chainsafe logo in the footer next to the 'Audit' mention. (to avoid deploying the website twice)

**Comment by andfletcher** [comment]
@olympe-silve do we have a logo that we can use for chainsaf that you can link? Also, do they have any min size requirements in their brand guidelines that we need to take into account?

**Comment by olympe-silve** [comment]
yes I have exported a small one, it is [here](https://drive.google.com/file/d/1hztYn1LF5HnlL-X1vLGTKn3-CiH-IdeX/view?usp=share_link)

All the other logos for the "backed by" section are [here](https://drive.google.com/file/d/1hztYn1LF5HnlL-X1vLGTKn3-CiH-IdeX/view?usp=share_link)

**Comment by andfletcher** [comment]
Since the logo provided from chainsafe does not really work on our website since we have a dark background I pinged chainsafe if they are ok with us using the one created, or if they have one, that works with a dark background

Before we dont get a confirmation lets not add the one we have.

**Comment by manuelwedler** [comment]
@andfletcher I guess they didn't respond yet, right?

**Comment by andfletcher** [comment]
@manuelwedler please go ahead without the chainsafe logo

**Comment by andfletcher** [comment]
We do have the chainsafe svg file now which olympe will resize and then we will get the approval from them if we can use it. however Olympe will not be able to do this today so please go ahead

**Comment by manuelwedler** [comment]
Alright!
