### ISSUE TITLE
Too large text on https://www.beamerbridge.com/

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/www.beamerbridge.com#4]
@olympe-silve 
The text on our website looks too large:

![image](https://user-images.githubusercontent.com/1312091/162695444-c267d72e-fc77-4534-b657-74f729e90df4.png)

I am not sure whether that was intentional, but at least for me it looks quite strange.
Notice that scaling the page results in a gap between the bottom of the text and the next section:

![image](https://user-images.githubusercontent.com/1312091/162695701-a5661f92-59be-4ecd-b619-025764f6bf7a.png)

**Comment by istankovic** [comment]
@olympe-silve any changes related to this? The text is still too large.

**Comment by olympe-silve** [comment]
> @olympe-silve any changes related to this? The text is still too large.

This will be addressed for the v2. I'm not responsible of implementation for the responsiveness.

**Comment by andfletcher** [comment]
Closing since this is beeing addressed as part of https://github.com/beamer-bridge/marketing/issues/63
