### ISSUE TITLE
Change background image to reflect currently supported networks

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/www.beamerbridge.com#47]
Since we are launching on Ethereum, the website and the app need to be refreshed by friday.

To dos:
- [x] Updating the background to include the Ethereum logo and put the Boba logo more in back

**Comment by olympe-silve** [comment]
Could you check out what it looks like with [this one](https://drive.google.com/file/d/1Mj3JZDlU3p2D9wt1lviog3D48e0s9GVZ/view?usp=share_link) ?

**Comment by GabrielBuragev** [comment]
Closed in #48
