### ISSUE TITLE
Replace invite link on both app and website footers

### ISSUE THREAD

**Issue by DBecane** [beamer-bridge/www.beamerbridge.com#54]
We've disabled all invite links from our Discord, except for the official server link. Can you please replace the old URL with this one: https://discord.com/invite/beamerbridge when clicking on the little Discord icon on both Website and App footers? 🙏

**Comment by compojoom** [comment]
Can we have a .gg url please? I need it for l2beat. They expect that the discord url coms from a .gg domain and not .com...

**Comment by compojoom** [comment]
Ok, for the record this: https://discord.gg/beamerbridge seems to correct redirect to https://discord.com/invite/beamerbridge
