### ISSUE TITLE
Edit Website + App banner

### ISSUE THREAD

**Issue by DBecane** [beamer-bridge/www.beamerbridge.com#67]
## Description 

Our community and users can misunderstand the wording "free fees" on ou website and app banners. They might think gas fees are covered while they are not. Therefore, the suggestion was made to clarify that only the bridging fees are covered. 

My suggestion is to use: 
`Enjoy 0 bridging fees for transfers over $250 from any L2 ($500 from L1). Limited offer!`

**Comment by DBecane** [comment]
@andfletcher adding the time pressure for people to bridge now

**Comment by GabrielBuragev** [comment]
Isn't this a very long text? This might not look good on mobile devices :S
I'll post screenshots here once i try it out.

**Comment by DBecane** [comment]
Let's try and see- let's fit it in 2 rows instead of one for example:

`Enjoy 0 bridging fees for transfers over $250 from any L2 ($500 from L1). 
                                                   Limited offer!`

**Comment by andfletcher** [comment]
@DBecane lets just remove the limited offer!.
