### ISSUE TITLE
Missing prominent links on our site

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/www.beamerbridge.com#7]
@dina @olympe-silve @czepluch I think we should at least include prominent links to the following on our site:

- the main github repo (for people willing to contribute)
- the `run-your-own-agent` repo (not sure about this one but I feel like it could be mentioned for potential LPs)
- our Discord server

**Comment by czepluch** [comment]
Did you scroll to the bottom of the site? That's usually where these kind of links are located.

**Comment by olympe-silve** [comment]
This issue should be a comment on #1 
I'm closing it and merging it.
